services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
